# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('data_bought', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
