# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
